[run]
dev = "cd proxy-mago-base && nix run nixpkgs#php82 -- -S 0.0.0.0:8080 -t public bin/router.php"
build = "cd proxy-mago-base && nix run nixpkgs#php82 -- -l app/CdnSession.php"
"build:dev" = "cd proxy-mago-base && nix run nixpkgs#php82 -- -l app/CdnSession.php"
